platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/build-kubo-deployment-tarball.sh

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: gcs-kubo-release-tarball-untested
- name: kubo-version
outputs:
- name: kubo-deployment-tarball
