platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/git-bosh
    tag: stable
run:
  path: git-kubo-ci/scripts/configure-slack-notification.sh

inputs:
- name: slackers
- name: git-kubo-ci
- name: git-kubo-deployment
- name: git-kubo-release

outputs:
- name: slack-notification
