---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/main-bosh-docker

inputs:
- name: kubo-ci
- name: release

outputs:
- name: compiled-release

run:
  path: kubo-ci/scripts/export-release.sh
