platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-upgrade-tests.sh
params:
  DEPLOYMENT_NAME:
  INTERNET_ACCESS: true
  ENABLE_MULTI_AZ_TESTS: false
  IAAS:

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
- name: gcs-kubo-release-tarball
- name: bosh-command
