---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: kubo-lock

params:
  DEPLOYMENT_NAME: ci-service
  ERRAND_NAME: ~
  INSTANCE: ~

run:
  path: git-kubo-ci/scripts/run-errand.sh
