platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-upgrade-tests.sh
params:
  DEPLOYMENT_NAME:
  INTERNET_ACCESS: true

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
- name: gcs-bosh-state
- name: gcs-bosh-creds
- name: gcs-kubo-release-tarball
- name: gcs-kubeconfig
- name: bosh-command
- name: gcs-load-balancer-vars
- name: director_uuid
- name: stemcell
