platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-integration-tests.sh

params:
  DEPLOYMENT_NAME: ci-service
  ENABLE_MULTI_AZ_TESTS: true
  ENABLE_OSS_ONLY_TESTS: true
  ENABLE_PERSISTENT_VOLUME_TESTS: true
  ENABLE_K8S_LBS_TESTS: true
  ENABLE_CIDR_TESTS: false
  CIDR_VARS_FILE: manifests/vars-files/default-cidrs.yml
  KUBECONFIG_FILE: config
  HPA_TIMEOUT: 210s

inputs:
  - name: git-kubo-ci
  - name: gcs-kubeconfig
