platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/conformance
    tag: stable
run:
  path: git-kubo-ci/scripts/run-conformance-tests.sh

params:

inputs:
  - name: git-kubo-ci
  - name: gcs-kubeconfig

