platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/set-kubo-release-version-in-manifest.sh

params:
  IS_FINAL:

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: kubo-version
  - name: kubo-release-tarball
outputs:
  - name: git-kubo-deployment-output
