platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/update-cloud-config.sh
  args:
  - source-json/source.json

params:
  OPS:

inputs:
- name: git-kubo-ci
- name: source-json
- name: kubo-lock
- name: git-kubo-deployment
