platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/install-bosh.sh
params:
  GCP_SERVICE_ACCOUNT:

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
- name: gcs-bosh-state
- name: gcs-bosh-creds
outputs:
- name: bosh-state
- name: bosh-creds
