- type: replace
  path: /instance_groups/name=worker/networks
  value:
  - name: default-((deployment_name))

- type: replace
  path: /instance_groups/name=apply-addons/networks
  value:
  - name: default-((deployment_name))

- type: replace
  path: /instance_groups/name=master/networks
  value:
  - name: default-((deployment_name))
