## Add ha-proxy
- type: replace
  path: /instance_groups/-
  value:
    name: haproxy
    instances: 1
    networks:
    - name: default
    stemcell: default
    vm_type: minimal
    azs:
    - z1
    jobs:
      - name: haproxy
        release: haproxy
        properties:
          ha_proxy:
            backend_port: 30303

- type: replace
  path: /releases/-
  value:
    name: haproxy
    url: https://github.com/iainsproat/cfcr-haproxy-boshrelease/releases/download/v8.7.1/cfcr-haproxy-8.7.1.tgz
    sha1: 9fd2d2eaac3bee50643a537d69227f7e01ed32c5
    version: 8.7.1

## Multi-AZ workers
- type: replace
  path: /instance_groups/name=worker/azs
  value: [ z1, z2, z3 ]

- type: replace
  path: /instance_groups/name=master/instances
  value: 3
- type: replace
  path: /instance_groups/name=master/azs
  value: [ z1, z2, z3 ]
